"""This file was auto-generated by NeuroPype."""

import sys
sys.path.append("C:\\Program Files\\Intheon\\NeuroPype Enterprise Suite (64-bit)\\NeuroPype Enterprise")

# import os
# #os.chdir('/cygdrive/C/Program Files/Intheon/NeuroPype Enterprise Suite (64-bit)/NeuroPype Enterprise')
# os.chdir("C:\\Program Files\\Intheon\\NeuroPype Enterprise Suite (64-bit)\\NeuroPype Enterprise")

from neuropype.nodes import *
from neuropype.engine import Graph, CPE



# create nodes
node1 = ImportEDF(filename='C:/Users/suhas/Desktop/prjs/golf_processing/data/0261/0261/026111501.ebs.edf')
node2 = LSLInput(query="name='MyOutputStream'")
node3 = StreamData()
node4 = LSLOutput(stream_name='MyOutputStream', stream_type='EEG', source_id='myuniquesourceid04536357', send_markers=True, marker_name='MyOutputStream-markers')
node5 = TimeSeriesPlot()
node6 = ImportSET(filename='MotorImageryTrainTest.set')
node7 = DejitterTimestamps()
node8 = IIRFilter(order=0, frequencies=[1, 2], mode='highpass', stop_atten=40.0)
node9 = MovingWindow(window_length=3)
node10 = MultitaperSpectrum()
node11 = SpectrumPlot(stream_name='', initial_dims=[], one_over_f_correction=True, always_on_top=True)

# create flow graph
patch = Graph()
patch.connect((node1, 'data'), (node3, 'data'))
patch.connect((node3, 'data'), (node4, 'data'))
patch.connect((node2, 'data'), (node5, 'data'))
patch.connect((node2, 'data'), (node7, 'data'))
patch.connect((node7, 'data'), (node8, 'data'))
patch.connect((node8, 'data'), (node9, 'data'))
patch.connect((node9, 'data'), (node10, 'data'))
patch.connect((node10, 'data'), (node11, 'data'))

# create CPE instance and run it
cpe = CPE(graph=patch)
cpe.loop_run()

